spring:
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    leader:
      url: jdbc:postgresql://localhost:5432/ecommerce?ssl=false&sslmode=disable
      username: postgres
      password: 12345
    follower:
      url: jdbc:postgresql://localhost:5432/ecommerce?ssl=false&sslmode=disable
      username: postgres
      password: 12345

logging:
  level:
    org.hibernate.sql: TRACE

    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
